### ISSUE TITLE
Using isolation lower and higher MZ values as scan number ranges?

### ISSUE THREAD

**Issue by fcyu** [Nesvilab/MSBooster#3]
Hi Kevin @yangkl96 .

The following codes used isolation lower and higher MZ values as scan numbers. Can you fix them (and the related codes)?

https://github.com/Nesvilab/MSBooster/blob/4a9466242093fe68d541b4115be191fcbcd21d26/src/main/java/Features/PercolatorFormatter.java#L399-L400

https://github.com/Nesvilab/MSBooster/blob/4a9466242093fe68d541b4115be191fcbcd21d26/src/main/java/Features/PercolatorFormatter.java#L417-L418

Thanks,

Fengchao

**Comment by yangkl96** [comment]
Hi Fengchao,

Thanks for pointing this out, the naming is confusing. `scanNumbers` is a rangemap where I query isolation window ranges and get back the scan numbers that may overlap with these ranges. I will change the naming to be clearer, but I am indeed using these values as isolation window boundaries
