### ISSUE TITLE
Please generate the edited pin file with the proper header if the input pin file is empty

### ISSUE THREAD

**Issue by fcyu** [Nesvilab/MSBooster#6]
I was analyzing some files and one of them had the blank pin file (only had the header but no other rows). MSBooster printed something like `2024-11-27 09:56:46 [INFO] - test\H_1\file1.pin is empty. Will not process this file.` and didn't generate the edited pin file, which crashed the following Percolator because Percolator was using the edited pin file as input.

In this case, please let MSBooster generate an blank edited pin file with the header only so that the workflow can proceed.

Thanks,

Fengchao

**Comment by fcyu** [comment]
Thanks. The edited pin file should have those new columns that are supposed in the **edited** pin file, not only those in the original pin file. Basically, you should treat the blank pin file as a normal pin file to generated the edited pin file.

Best,

Fengchao

**Comment by yangkl96** [comment]
Can you try this one? It checks if the pin file is empty and then writes a new empty edited pin

https://www.dropbox.com/scl/fo/ov1bmjxhws3dhxcn9tuj0/AG8fXDH1LyPB07ikL5jO1hI?rlkey=98en8cwgvsq7wkppwlkryjw0b&st=0zutfwcb&dl=0

**Comment by fcyu** [comment]
It looks good now. Thanks. 

Please also push the code.

Best,

Fengchao
